# Generated by Django 3.1.7 on 2021-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='charity',
            field=models.CharField(choices=[('Marie Curie', 'Marie Curie'), ('Animal Welfare Fund', 'Animal Welfare Fund')], default='Marie Curie', max_length=254),
        ),
    ]
