# Generated by Django 3.1.7 on 2021-02-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='charity',
            field=models.CharField(choices=[('Marie Curie', 'Marie Curie'), ('Animal Welfare Fund', 'Animal Welfare Fund'), ('GiveWel', 'GiveWell'), ('Against Malaria Foundation', 'Against Malaria Foundation'), ('Development Media International', 'Development Media International'), ('Evidence Action', 'Evidence Action'), ('Fistula Foundation', 'Fistula Foundation'), ('Fred Hollows Foundation', 'Fred Hollows Foundation'), ('GiveDirectly', 'GiveDirectly'), ('Helen Keller International', 'Helen Keller International'), ('Innovations for Proverty Action', 'Innovations for Proverty Action'), ('Iodine Global Network', 'Iodine Global Network'), ('Living Goods', 'Living Goods'), ('Malaria Consortium', 'Malaria Consortium'), ('New Incentives', 'New Incentives'), ('One Acre Fund', 'One Acre Fund'), ('Oxfam', 'Oxfam'), ('Population Services International', 'Population Services International'), ('Project Healthy Children', 'Project Healthy Children'), ('SCI Foundation', 'SCI Foundation'), ('Seva', 'Seva'), ('Village Enterprise', 'Village Enterprise'), ('Zusha!', 'Zusha!')], default='Marie Curie', max_length=254),
        ),
    ]
