# Generated by Django 3.1.7 on 2021-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210222_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='charity',
            field=models.CharField(choices=[('Against Malaria Foundation', 'Against Malaria Foundation'), ('Age UK', 'Age UK'), ("Alzheimer's Research UK", "Alzheimer's Research UK"), ("Alzheimer's Society", "Alzheimer's Society"), ('Animal Welfare Fund', 'Animal Welfare Fund'), ("Barnardo's", "Barnardo's"), ('Battersea Dogs and Cats Home', 'Battersea Dogs and Cats Home'), ('Bowel Cancer UK', 'Bowel Cancer UK'), ('Breast Cancer Care', 'Breast Cancer Care'), ('British Heart Foundation', 'British Heart Foundation'), ('British Red Cross', 'British Red Cross'), ('Cancer Research UK', 'Cancer Research UK'), ('Children in Need', 'Children in Need'), ('Comic Relief', 'Comic Relief'), ('Dementia UK', 'Dementia UK'), ('Development Media International', 'Development Media International'), ('Diabetes UK', 'Diabetes UK'), ('Dogs Trust', 'Dogs Trust'), ('Evidence Action', 'Evidence Action'), ('Fistula Foundation', 'Fistula Foundation'), ('Fred Hollows Foundation', 'Fred Hollows Foundation'), ('GiveDirectly', 'GiveDirectly'), ('GiveWel', 'GiveWell'), ('Great Ormond Street Hospital', 'Great Ormond Street Hospital'), ('Guide Dogs', 'Guide Dogs'), ('Hearing Dogs for Deaf People', 'Hearing Dogs for Deaf People'), ('Helen Keller International', 'Helen Keller International'), ('Help for Heroes', 'Help for Heroes'), ('Innovations for Proverty Action', 'Innovations for Proverty Action'), ('Iodine Global Network', 'Iodine Global Network'), ('Keep Britain Tidy', 'Keep Britain Tidy'), ('Living Goods', 'Living Goods'), ('Macmillan Cancer Support', 'Macmillan Cancer Support'), ('Malaria Consortium', 'Malaria Consortium'), ('Marie Curie', 'Marie Curie'), ('Mind', 'Mind'), ('NSPCC', 'NSPCC'), ('National Trust', 'National Trust'), ('New Incentives', 'New Incentives'), ('One Acre Fund', 'One Acre Fund'), ('Oxfam', 'Oxfam'), ('PDSA', 'PDSA'), ("Parkinson's UK", "Parkinson's UK"), ('Population Services International', 'Population Services International'), ('Prince of Wales Trust', 'Price of Wales Trust'), ('Project Healthy Children', 'Project Healthy Children'), ('Prostate Cancer UK', 'Prostate Cancer UK'), ('RNLI Lifeboats', 'RNLI Lifeboats'), ('RSPB', 'RSPB'), ('RSPCA', 'RSPCA'), ('SCI Foundation', 'SCI Foundation'), ('Salvation Army', 'Salvation Army'), ('Samaritans', 'Samaritans'), ('Save the Children', 'Save the Children'), ('Seva', 'Seva'), ('Shelter', 'Shelter'), ('St. John Ambulance', 'St. John Ambulance'), ('Teenage Cancer Trust', 'Teenage Cancer Trust'), ('The Donkey Sanctuary', 'The Donkey Sanctuary'), ('The Fairtrade Foundation', 'The Fairtrade Foundation'), ('UNICEF', 'UNICEF'), ('Village Enterprise', 'Village Enterprise'), ('WWF', 'WWF'), ('Zusha!', 'Zusha!')], default='', max_length=254),
        ),
    ]
